import type { Listing } from '../../../shared/domain';
import { listingSchema } from '../../../shared/schemas';
import { wanToNtd } from '../../../shared/utils';
import type { RawSinyiSaleListing } from './types';
import { isProductionCity } from '../../scope/production';
const num = (v?: string) => { const m = v?.replace(/,/g, '').match(/\d+(?:\.\d+)?/); return m ? Number(m[0]) : undefined; };
const integer = (v?: string) => { const value = num(v); return value !== undefined && Number.isInteger(value) ? value : undefined; };
const money = (v?: string) => { const n = num(v); return n === undefined || /待定|洽詢|來電/.test(v ?? '') ? undefined : /萬/.test(v ?? '') ? wanToNtd(n) : Math.round(n); };
const btype = (v?: string): Listing['buildingType'] | undefined => !v ? undefined : /住宅大樓|大樓/.test(v) ? 'RESIDENTIAL_HIGHRISE' : /華廈/.test(v) ? 'MIDRISE' : /公寓|套房/.test(v) ? 'APARTMENT' : /透天|別墅/.test(v) ? 'TOWNHOUSE' : 'UNKNOWN';
const listingType = (v?: string): Listing['listingType'] => /預售/.test(v ?? '') ? 'PRESALE' : /新成屋|新古屋/.test(v ?? '') ? 'NEW' : 'USED';
export function normalizeSinyiSale(raw: RawSinyiSaleListing, observedAt = new Date().toISOString()): Listing { if (!raw.sourceListingId) throw new Error('VALIDATION_ERROR: missing sourceListingId'); const p = raw.parkingText ? { hasParking: true as const, parkingType: /坡道平面/.test(raw.parkingText) ? 'RAMP_FLAT' as const : /坡道機械/.test(raw.parkingText) ? 'RAMP_MECHANICAL' as const : 'UNKNOWN' as const } : {}; return listingSchema.parse({ id: `sinyi-sale:${raw.sourceListingId}`, sourceId: 'sinyi-sale', sourceListingId: raw.sourceListingId, listingType: listingType(raw.listingTypeText), title: raw.title, city: raw.city, district: raw.district, address: raw.addressText, totalPrice: money(raw.totalPriceText), unitPrice: money(raw.unitPriceText), buildingArea: num(raw.buildingAreaText), rooms: integer(raw.roomsText), halls: integer(raw.hallsText), bathrooms: integer(raw.bathroomsText), floor: integer(raw.floorText), totalFloors: integer(raw.totalFloorsText), buildingAge: num(raw.buildingAgeText), buildingType: btype(raw.buildingTypeText), ...p, nearestMrtStation: raw.mrtText, sourceUrl: raw.sourceUrl, status: 'ACTIVE', firstSeenAt: observedAt, lastSeenAt: observedAt, lastCheckedAt: observedAt, relistCount: 0, missingSuccessCount: 0, contentHash: JSON.stringify([raw.title, raw.listingTypeText, raw.totalPriceText, raw.unitPriceText, raw.buildingAreaText, raw.roomsText, raw.floorText, raw.buildingTypeText, raw.parkingText]), rawDataHash: JSON.stringify(raw.raw), createdAt: observedAt, updatedAt: observedAt }) as Listing; }
export function normalizeSinyiSaleInProduction(raw: RawSinyiSaleListing, observedAt: string): Listing { if (!isProductionCity(raw.city)) throw new Error('OUT_OF_SCOPE: city is not in production scope'); if (!raw.district) throw new Error('INVALID_LISTING: missing district'); return normalizeSinyiSale(raw, observedAt); }
