import { describe, expect, it } from 'vitest';
import { classifyNewHouseHttpFailure, collectNewHousePages } from '../crawler/collectors/591-newhouse/collector';
import { normalizeNewHouse } from '../crawler/collectors/591-newhouse/normalizer';
import { parseNewHousePage } from '../crawler/collectors/591-newhouse/parser';
import { processListingObservation } from '../crawler/lifecycle/service';
import { ListingLifecycleStore } from '../crawler/lifecycle/store';
import type { ListingObservation } from '../crawler/lifecycle/types';

const raw = { projectId: 'nh-123', projectName: '晴朗新建案', projectType: '預售屋', city: '台北市', district: '信義區', priceText: '1800～2600萬', unitPriceText: '78～92萬/坪', areaText: '28～45坪', roomText: '2～4房', mrtText: '市政府站', sourceUrl: 'https://newhouse.591.com.tw/home/nh-123', raw: { projectId: 'nh-123', projectType: '預售屋' } };
describe('591 newhouse collector', () => {
  it('parses and normalizes a presale project with ranges', () => { const result = parseNewHousePage([raw], 1); expect(result.status).toBe('SUCCESS'); const listing = normalizeNewHouse(result.items[0]!); expect(listing.id).toBe('591-newhouse:nh-123'); expect(listing.listingType).toBe('PRESALE'); expect(listing.minTotalPrice).toBe(18_000_000); expect(listing.maxTotalPrice).toBe(26_000_000); expect(listing.minUnitPrice).toBe(780_000); expect(listing.maxUnitPrice).toBe(920_000); expect(listing.minBuildingArea).toBe(28); expect(listing.maxRooms).toBe(4); expect(listing.totalPrice).toBeUndefined(); });
  it('maps new house and unknown types conservatively', () => { expect(normalizeNewHouse({ ...raw, projectId: 'nh-124', projectType: '新成屋' }).listingType).toBe('NEW'); expect(normalizeNewHouse({ ...raw, projectId: 'nh-125', projectType: '新建案' }).listingType).toBe('UNKNOWN'); expect(normalizeNewHouse({ ...raw, projectId: 'nh-126', priceText: '價格待定', areaText: '坪數未公開' }).minTotalPrice).toBeUndefined(); });
  it('supports exact values and URL fallback ID', () => { const listing = normalizeNewHouse({ ...raw, projectId: undefined, sourceUrl: 'https://newhouse.591.com.tw/project?id=999', priceText: '2388萬', unitPriceText: '88萬/坪', areaText: '32坪', roomText: '2房' }); expect(listing.id).toBe('591-newhouse:999'); expect(listing.totalPrice).toBe(23_880_000); expect(listing.buildingArea).toBe(32); expect(listing.rooms).toBe(2); });
  it('detects duplicate pages and partial failures', async () => { const duplicate = await collectNewHousePages(async () => [raw], 3); expect(duplicate.warnings[0]).toContain('duplicate'); let page = 0; const partial = await collectNewHousePages(async () => { page += 1; if (page === 2) throw new Error('TIMEOUT'); return [raw]; }, 3); expect(partial.status).toBe('PARTIAL'); });
  it('integrates normalized listing with Phase 04 lifecycle and is replay-safe', () => { const store = new ListingLifecycleStore(); const listing = normalizeNewHouse(raw, '2026-08-24T08:20:00+08:00'); const observation = { ...listing, observedAt: '2026-08-24T08:20:00+08:00' } as ListingObservation; processListingObservation(store, observation); processListingObservation(store, observation); expect(store.count('listings')).toBe(1); expect(store.count('listing_events')).toBe(1); expect(store.count('raw_snapshots')).toBe(1); const changed = normalizeNewHouse({ ...raw, priceText: '1750～2500萬', raw: { ...raw.raw, priceText: '1750～2500萬' } }, '2026-08-24T09:20:00+08:00'); processListingObservation(store, { ...changed, observedAt: '2026-08-24T09:20:00+08:00' } as ListingObservation); expect(store.events(listing.id).map((event) => event.eventType)).toContain('CONTENT_CHANGED'); store.close(); });
  it('returns FAILED for malformed source schema', () => { expect(parseNewHousePage({ unexpected: true }, 1).status).toBe('FAILED'); });
  it('does not bypass access boundaries', () => { expect(classifyNewHouseHttpFailure(403)).toEqual({ status: 'FAILED', errorCode: 'ACCESS_DENIED', retryable: false }); expect(classifyNewHouseHttpFailure(429).errorCode).toBe('RATE_LIMITED'); });
});
