import { describe, expect, it } from 'vitest';
import { processListingObservation, reconcileMissing } from '../crawler/lifecycle/service';
import { ListingLifecycleStore } from '../crawler/lifecycle/store';
import type { ListingObservation } from '../crawler/lifecycle/types';

const at = (n: number) => `2026-08-24T${String(8 + n).padStart(2, '0')}:20:00+08:00`;
const observation = (overrides: Partial<ListingObservation> = {}): ListingObservation => ({ id: '591-sale:1', sourceId: '591-sale', sourceListingId: '1', listingType: 'USED', contentHash: 'content-1', rawDataHash: 'raw-1', totalPrice: 26_800_000, unitPrice: 900_000, title: 'Synthetic listing', observedAt: at(0), ...overrides });
const run = (n: number, status: 'SUCCESS' | 'PARTIAL' | 'FAILED' = 'SUCCESS') => ({ id: `run-${n}-${status}`, sourceId: '591-sale', startedAt: at(n), finishedAt: at(n), status, listingCount: 0 });

describe('Listing lifecycle', () => {
  it('creates ACTIVE listing, first price history, event and snapshot', () => { const store = new ListingLifecycleStore(); const result = processListingObservation(store, observation()); expect(result.listing.status).toBe('ACTIVE'); expect(store.count('listings')).toBe(1); expect(store.count('listing_price_history')).toBe(1); expect(store.events(result.listing.id)[0]?.eventType).toBe('LISTING_DISCOVERED'); expect(store.count('raw_snapshots')).toBe(1); store.close(); });
  it('is idempotent for the same observation and raw hash', () => { const store = new ListingLifecycleStore(); const first = processListingObservation(store, observation()); processListingObservation(store, observation()); expect(store.count('listings')).toBe(1); expect(store.count('listing_price_history')).toBe(1); expect(store.events(first.listing.id)).toHaveLength(1); expect(store.count('raw_snapshots')).toBe(1); store.close(); });
  it('records price decrease/increase but not unknown-to-known as increase', () => { const store = new ListingLifecycleStore(); processListingObservation(store, observation({ totalPrice: undefined, unitPrice: undefined })); processListingObservation(store, observation({ observedAt: at(1) })); expect(store.events('591-sale:1').map((event) => event.eventType)).not.toContain('PRICE_INCREASED'); processListingObservation(store, observation({ observedAt: at(2), totalPrice: 25_800_000, rawDataHash: 'raw-2', contentHash: 'content-2' })); expect(store.events('591-sale:1').map((event) => event.eventType)).toContain('PRICE_DECREASED'); processListingObservation(store, observation({ observedAt: at(3), totalPrice: 26_500_000, rawDataHash: 'raw-3', contentHash: 'content-3' })); expect(store.events('591-sale:1').map((event) => event.eventType)).toContain('PRICE_INCREASED'); store.close(); });
  it('preserves known price when observation omits price', () => { const store = new ListingLifecycleStore(); processListingObservation(store, observation()); const result = processListingObservation(store, observation({ observedAt: at(1), totalPrice: undefined, unitPrice: undefined, rawDataHash: 'raw-2' })); expect(result.listing.totalPrice).toBe(26_800_000); expect(store.histories('591-sale:1')).toHaveLength(1); store.close(); });
  it('restores missing and relists delisted without creating a new listing', () => { const store = new ListingLifecycleStore(); processListingObservation(store, observation()); reconcileMissing(store, run(1), new Set()); expect(store.getListing('591-sale:1')?.status).toBe('MISSING'); processListingObservation(store, observation({ observedAt: at(2), rawDataHash: 'raw-2' })); expect(store.events('591-sale:1').map((event) => event.eventType)).toContain('RESTORED'); reconcileMissing(store, run(3), new Set()); reconcileMissing(store, run(4), new Set()); reconcileMissing(store, run(5), new Set()); expect(store.getListing('591-sale:1')?.status).toBe('DELISTED'); processListingObservation(store, observation({ observedAt: at(6), rawDataHash: 'raw-5' })); expect(store.getListing('591-sale:1')?.relistCount).toBe(1); expect(store.events('591-sale:1').map((event) => event.eventType)).toContain('RELISTED'); expect(store.count('listings')).toBe(1); store.close(); });
  it('does not reconcile FAILED or PARTIAL runs', () => { const store = new ListingLifecycleStore(); processListingObservation(store, observation()); reconcileMissing(store, run(1, 'FAILED'), new Set()); reconcileMissing(store, run(2, 'PARTIAL'), new Set()); expect(store.getListing('591-sale:1')?.status).toBe('ACTIVE'); expect(store.getListing('591-sale:1')?.missingSuccessCount).toBe(0); store.close(); });
  it('keeps five snapshots per listing and three for another listing', () => { const store = new ListingLifecycleStore(); for (let i = 0; i < 7; i += 1) processListingObservation(store, observation({ observedAt: at(i), rawDataHash: `raw-${i}`, contentHash: `content-${i}` })); for (let i = 0; i < 3; i += 1) processListingObservation(store, observation({ id: '591-sale:2', sourceListingId: '2', observedAt: at(i), rawDataHash: `other-${i}`, contentHash: `other-${i}` })); expect(store.snapshots('591-sale:1')).toHaveLength(5); expect(store.snapshots('591-sale:2')).toHaveLength(3); store.close(); });
});
