import { parseCsvBytes } from '../collectors/moi/parser';
import { normalizeMoi } from '../collectors/moi/normalizer';
import type { MoiPipelineSummary } from '../collectors/moi/types';
import { createTransactionRepository, type TransactionRepository } from '../persistence/sqlite';
import { isMoiTransactionInRollingWindow, isProductionCity, isProductionDistrict } from '../scope/production';
import { addManifestCity, manifestCityMap } from '../collectors/moi/parser';
import type { Transaction } from '../../shared/domain';
export function normalizeMoiArchive(files: Record<string, Uint8Array>, referenceDate: string): Transaction[] { const cityByFile = files['manifest.csv'] ? manifestCityMap(files['manifest.csv']) : new Map<string, string>(); return Object.entries(files).filter(([sourceFile]) => sourceFile.endsWith('_lvr_land_a.csv') || sourceFile.endsWith('_lvr_land_b.csv')).flatMap(([sourceFile, bytes]) => parseCsvBytes(bytes, sourceFile).map((row) => normalizeMoi(addManifestCity(row, cityByFile.get(sourceFile))))).filter((transaction) => isProductionCity(transaction.city) && isProductionDistrict(transaction.city, transaction.district) && isMoiTransactionInRollingWindow(transaction.transactionDate, referenceDate)); }
export function runMoiCsvPipeline(bytes: Uint8Array, sourceFile: string, repository: TransactionRepository = createTransactionRepository(), options: { referenceDate?: string } = {}): MoiPipelineSummary { const summary: MoiPipelineSummary = { downloaded: 0, parsed: 0, normalized: 0, persisted: 0, skipped: 0, failed: 0, warnings: [] }; const rows = parseCsvBytes(bytes, sourceFile); summary.parsed = rows.length; const referenceDate = options.referenceDate ?? new Date().toISOString(); for (const row of rows) { try { const transaction = normalizeMoi(row); if (!isProductionCity(transaction.city) || !isMoiTransactionInRollingWindow(transaction.transactionDate, referenceDate)) { summary.skipped += 1; continue; } repository.upsert(transaction); summary.normalized += 1; summary.persisted += 1; } catch (error) { summary.skipped += 1; summary.failed += 1; summary.warnings.push(error instanceof Error ? error.message : 'UNKNOWN'); } } return summary; }
