import type { Listing } from '../../../shared/domain';
import { listingSchema } from '../../../shared/schemas';
import { wanToNtd } from '../../../shared/utils';
import type { RawYungchingSaleListing } from './types';
import { isProductionCity } from '../../scope/production';
const n = (v?: string) => { if (!v) return undefined; const m = v.replace(/,/g, '').match(/-?\d+(?:\.\d+)?/); return m ? Number(m[0]) : undefined; };
const money = (v?: string) => { const x = n(v); return x === undefined || /待定|洽詢|來電/.test(v ?? '') ? undefined : /萬/.test(v ?? '') ? wanToNtd(x) : Math.round(x); };
const type = (v?: string): Listing['listingType'] => /預售/.test(v ?? '') ? 'PRESALE' : /新成屋|新古屋/.test(v ?? '') ? 'NEW' : /中古/.test(v ?? '') ? 'USED' : 'UNKNOWN';
const building = (v?: string): Listing['buildingType'] | undefined => !v ? undefined : /住宅大樓|大樓/.test(v) ? 'RESIDENTIAL_HIGHRISE' : /華廈/.test(v) ? 'MIDRISE' : /公寓/.test(v) ? 'APARTMENT' : /透天|別墅/.test(v) ? 'TOWNHOUSE' : 'UNKNOWN';
const parking = (v?: string) => !v ? {} : { hasParking: true as const, parkingType: /坡道平面/.test(v) ? 'RAMP_FLAT' as const : /坡道機械/.test(v) ? 'RAMP_MECHANICAL' as const : 'UNKNOWN' as const };
export function normalizeYungchingSale(raw: RawYungchingSaleListing, observedAt = new Date().toISOString()): Listing { if (!raw.sourceListingId) throw new Error('VALIDATION_ERROR: missing sourceListingId'); const price = money(raw.totalPriceText); const p = parking(raw.parkingText); const result = { id: `yungching-sale:${raw.sourceListingId}`, sourceId: 'yungching-sale', sourceListingId: raw.sourceListingId, listingType: type(raw.raw.listingType as string | undefined), title: raw.title, city: raw.city, district: raw.district, address: raw.addressText, totalPrice: price, unitPrice: money(raw.unitPriceText), buildingArea: n(raw.buildingAreaText), rooms: n(raw.roomsText), halls: n(raw.hallsText), bathrooms: n(raw.bathroomsText), floor: n(raw.floorText), totalFloors: n(raw.totalFloorsText), buildingAge: n(raw.buildingAgeText), buildingType: building(raw.buildingTypeText), ...p, nearestMrtStation: raw.mrtText, sourceUrl: raw.sourceUrl, status: 'ACTIVE', firstSeenAt: observedAt, lastSeenAt: observedAt, lastCheckedAt: observedAt, relistCount: 0, missingSuccessCount: 0, contentHash: JSON.stringify([raw.title, raw.totalPriceText, raw.unitPriceText, raw.buildingAreaText, raw.roomsText, raw.floorText, raw.buildingTypeText, raw.parkingText]), rawDataHash: JSON.stringify(raw.raw), createdAt: observedAt, updatedAt: observedAt }; return listingSchema.parse(result) as Listing; }
export function normalizeYungchingSaleInProduction(raw: RawYungchingSaleListing, observedAt: string): Listing { if (!isProductionCity(raw.city)) throw new Error('OUT_OF_SCOPE: city is not in production scope'); if (!raw.district) throw new Error('INVALID_LISTING: missing district'); return normalizeYungchingSale(raw, observedAt); }
